# Generated by Django 2.1.5 on 2019-01-08 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BokeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'boketoken',
            },
        ),
        migrations.CreateModel(
            name='BokeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bokeuser',
            },
        ),
        migrations.AddField(
            model_name='boketoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.BokeUser'),
        ),
    ]
