# Generated by Django 2.1.5 on 2019-01-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('keyword', models.CharField(max_length=50, null=True)),
                ('describe', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('label', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(null=True, upload_to='upload')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('alias', models.CharField(max_length=10, null=True)),
                ('parent', models.CharField(max_length=10, null=True)),
                ('keywords', models.CharField(max_length=10, null=True)),
                ('describe', models.TextField(null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
